### PR TITLE
CITR-2896: Upgrade 'jackson-databind' to 2.8.9

### PR DESCRIPTION
**Pull request by indyaah**

### CODE REVIEW

**Review by maxhutch — CHANGES_REQUESTED** [review]
Please pin the versions with `[x.y.z]`

**Review by maxhutch — APPROVED** [review]

**Comment by indyaah** [comment]
@maxhutch : Is travic ci setup broken on this repo?

**Comment by maxhutch** [comment]
@indyaah it ran the first time, so I doubt its an issue with the setup.

**Comment by indyaah** [comment]
Closing and reopening PR just so that I can trigger a build.

**Review by maxhutch — APPROVED** [review]

**Pull request merged**
